core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls')),

    #Password Change Views
    path("password_change/", auth_views.PasswordChangeView.as_view(), name='password_change'),
    path("password_change/done/", auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    #Password Reset Views
    path("password_reset/", auth_views.PasswordResetView.as_view(), name='password_reset'),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path("", include('matrimony.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matrimony/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="matrimony"

urlpatterns = [
    path('', views.ProfileListView, name='profile_list'),
    path('<int:profile_id>', views.ProfileDetailView, name='profile_detail'),
    path('<int:profile_id>/delete', views.ProfileDeleteView, name='delete'),
    path('contact', views.ContactView, name='contact'),
    path('new_profile', views.ProfileFormView, name='new_profile'),
    path('father_profile', views.FatherProfileView, name='father_profile'),

]

matrimony/models.py
from typing import Iterable
from django.db import models
from django.conf import settings
from django.core.files.storage import FileSystemStorage

fs = FileSystemStorage(location=settings.MEDIA_ROOT)

# Create your models here.

class Religion(models.Model):
    name=models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
class Sect(models.Model):
    name=models.CharField(max_length=256)
    religion=models.ForeignKey(Religion, on_delete=models.CASCADE, related_name='Sects', null=True)

    def __str__(self):
        return self.name

class Caste(models.Model):
    name=models.CharField(max_length=256)

    def __str__(self):
        return self.name
    
class Hobby(models.Model):
    name=models.CharField(max_length=256)

    class Meta:
        verbose_name_plural="hobbies"
    
    def __str__(self):
        return self.name

class FatherProfile(models.Model):
    name=models.CharField(max_length=256)
    occupation=models.CharField(max_length=256, null=True, blank=True)

    def __str__(self):
        return self.name

 
class Profile(models.Model):
    GENDER_Choices=[
        ('M', 'Male'),
        ('F','Female')
        ]
    name=models.CharField(max_length=256, default="Unnamed")
    profile_pic=models.ImageField(null=True, blank=True)
    age=models.IntegerField()
    gender=models.CharField(max_length=1, choices=GENDER_Choices)
    occupation=models.CharField(max_length=256, null=True, blank=True)
    birth_date=models.DateField(null=True)
    is_married=models.BooleanField(default=False)
    email=models.EmailField(max_length=256, unique=True)

    religion=models.ForeignKey(Religion, on_delete=models.CASCADE, related_name='profiles', null=True)
    sect=models.ForeignKey(Sect, on_delete=models.CASCADE, related_name='profiles', null=True)
    caste=models.ForeignKey(Caste, on_delete=models.CASCADE, related_name='profiles', null=True)
    hobbies=models.ManyToManyField(Hobby, related_name='profiles')
    father=models.OneToOneField(FatherProfile, on_delete=models.CASCADE, related_name='Depandent', null=True)


    def save(self, *args, **kwargs):
        print(f"Data updated for {self.name}")
        super().save(*args, **kwargs)

    def __str__(self):
        return self.name

matrimony/forms.py
from django import forms

from django.core.validators import EmailValidator
from django.core.exceptions import ValidationError

from .models import Profile, FatherProfile


# 1. Defining Cutom Validator
def my_email_validator(email):
    if email.split('@')[1].split('.')[0].lower() == "hotmail":
         raise ValidationError("Email not Acceptable")


class ContactForm(forms.Form):
    name=forms.CharField(max_length=100)
    email=forms.CharField(validators=[EmailValidator(), my_email_validator])  
    verify_email = forms.CharField()                                          
    message=forms.CharField(widget=forms.Textarea)

    # 2. Custom Cleaning
    def clean(self):
        cleaned_data = super().clean()

        name= cleaned_data.get('name')
        cleaned_data['email']= cleaned_data.get('email').lower()
        cleaned_data['verify_email']= cleaned_data.get('verify_email').lower()
        message= cleaned_data.get('message')

        if cleaned_data.get('email') != cleaned_data.get('verify_email'):
            raise forms.ValidationError("Email Mismatched")
        
        return cleaned_data


class ProfileForm(forms.ModelForm):

    class Meta:
        model = Profile
        fields = "__all__"
        # fields = ['name', 'age', 'gender']
        # exclude = ['is_married', 'name', 'age', 'profile_pic']
        

class FatherProfileForm(forms.ModelForm):

    class Meta:
        model = FatherProfile
        fields = "__all__"
        # fields = ['name', 'age', 'gender']
        # exclude = ['is_married', 'name', 'age', 'profile_pic']

matrimony/views.py
from django.shortcuts import render, redirect
from .models import *
from .forms import ContactForm, ProfileForm, FatherProfileForm
from django.forms import formset_factory
from django.contrib.auth.decorators import login_required


# Create your views here.

def ProfileListView(request):
    profiles = Profile.objects.all()
    user = request.user
    return render(request, 'matrimony/profile_list.html', {'profiles': profiles, 'user': user})

def ProfileDetailView(request, profile_id):
    profile = Profile.objects.get(id=profile_id)
    user = request.user
    return render(request, 'matrimony/profile_detail.html', {'profile': profile, 'user': user})

@login_required
def ProfileDeleteView(request, profile_id):
    profile=Profile.objects.get(id=profile_id)
    profile.delete()
    return redirect ('matrimony:profile_list')

def ContactView(request):

    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            print(f"NAME: {form.cleaned_data['name']}")
            print(f"EMAIL: {form.cleaned_data['email']}")
            print(f"MESSAGE: {form.cleaned_data['message']}")
    else:
        form = ContactForm()

    user = request.user
    return render(request, 'matrimony/contact.html', {'form': form, 'user': user})


@login_required
def ProfileFormView(request):

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('matrimony:profile_list')
    else:
        form = ProfileForm()

    return render(request, 'matrimony/new_profile.html', {'form': form})


@login_required
def FatherProfileView(request):

    if request.method == 'POST':
        form = FatherProfileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('matrimony:profile_list')
    else:
        form = FatherProfileForm()

    return render(request, 'matrimony/father_profile.html', {'form': form})
 

matrimony/templates/matrimony/contact.html
{% extends "base.html" %}


{% block title %}
<title>Contact Us</title>
{% endblock%}

    {% block content %}
    
    <h1>Contact Form!</h1>
    <form method="post">
        <div class="form-group">
            {{ form.name.label_tag }}
            <input type="text" class="form-control" name="{{ form.name.name }}"></br> 
        </div>
        <div class="form-group">
            {{ form.email.label_tag }}  
            <input type="email" class="form-control" name="{{ form.email.name }}"></br>        
        </div>
        <div class="form-group">
            {{ form.verify_email.label_tag }}
            <input type="email" class="form-control" name="{{ form.verify_email.name }}"></br>         
        </div>
        <div class="form-group">
            {{ form.message.label_tag }} 
            <textarea class="form-control" name="{{ form.message.name }}" ></textarea></br>         
        </div>

        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

    {% endblock content %}

matrimony/templates/matrimony/father_profile.html
{% extends "base.html" %}


{% block title %}
<title>Add Fatherr's Profile</title>
{% endblock%}


    {% block content %}
    
    <h1>Add Fatherr's Profile! </h1>
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

    {% endblock content %}

matrimony/templates/matrimony/new_profile.html
{% extends "base.html" %}


{% block title %}
<title>Add New Profile</title>
{% endblock%}


    {% block content %}
    
    <h1>Add New Profile! </h1>
    <form method="post" enctype="multipart/form-data">
        {{ form.as_p }}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Submit">
    </form>

    {% endblock content %}

matrimony/templates/matrimony/profile_detail.html
{% extends "base.html" %}


{% block title %}
<title>Profile Detail</title>
{% endblock%}

{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-8 offset-md-2">
            <div class="card">
                <div class="row no-gutters">
                    <div class="col-md-4">
                        <img src="{{ profile.profile_pic.url }}" class="card-img" alt="Profile picture">
                    </div>
                    <div class="col-md-8">
                        <div class="card-body">
                            <h5 class="card-title">{{ profile.name }}</h5>
                            <p class="card-text"><small class="text-muted">{{ profile.age }} years old</small></p>
                            <p class="card-text">{{ profile.bio }}</p>
                            <p class="card-text">
                                <strong>Occupation:</strong> {{ profile.occupation }}<br>
                                <strong>Date of Birth:</strong> {{ profile.birth_date }}<br>
                                <strong>Marital Status:</strong> {{ profile.is_married|yesno:"Married,Single" }}<br>
                                <strong>Email:</strong> {{ profile.email }}<br>
                                <strong>Hobbies:</strong> 
                                <ul>
                                {% for hobby in profile.hobbies.all %}
                                <li>{{ hobby }}</li>
                                {% endfor %}
                                </ul>
                                <strong>Caste:</strong> {{ profile.caste }}<br>
                                <strong>Sect:</strong> {{ profile.sect }}<br>
                                <strong>Religion:</strong> {{ profile.religion }}<br>
                                <strong>Father's Name:</strong> {{ profile.father.name }}<br>
                                <strong>Father's Occupation:</strong> {{ profile.father.occupation }}<br>
                            </p>
                            <a href="{% url 'matrimony:profile_list' %}" class="btn btn-primary">Back</a>
                            <a href="{% url 'matrimony:delete' profile.id %}" class="btn btn-danger">Delete</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<p></p>
{% endblock content %}

matrimony/templates/matrimony/profile_list.html
{% extends "base.html" %}

{% block title %}
<title>Profile List</title>
{% endblock%}


{% block content %}

<p></p>
<div class="container">
    <form class="container-fluid justify-content-start">
        <div class="column btn btn-success me-2 type="button">
            <a href="{% url 'matrimony:new_profile' %}" class="btn btn-warning">Add Profile</a>
        </div><hr>
    
        <div class="column btn btn-success me-2" type="button">
            <a href="{% url 'matrimony:father_profile' %}" class="btn btn-warning">Add Father's Profile</a>
        </div><hr>
    </form>


    <div class="row">
        {% if profiles %}
        {% for profile in profiles %}
        <div class="col-md-4">
            <div class="card" style="width: 18rem; height: auto;">
                <img src="{{ profile.profile_pic.url }}" class="card-img-top" alt="Profile Photo">
                <div class="card-body">
                    <h5 class="card-title">{{ profile.name }}</h5>
                    <p class="card-text">Some quick example text to build on the card title and make up the bulk of the
                        card's content.</p>
                    <a href="{% url 'matrimony:profile_detail' profile.id %}" class="btn btn-primary">Read More...</a>
                </div>
            </div>
            <p></p>
        </div>
        {% endfor %}
        {% endif %}

    </div>
</div>

{% endblock content %}