accounts/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="accounts"

urlpatterns = [
    path('register', views.register, name='register'),
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('delete', views.delete_view, name='delete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("accounts/", include('accounts.urls')),

    #Password Change Views
    path("password_change/", auth_views.PasswordChangeView.as_view(), name='password_change'),
    path("password_change/done/", auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),

    #Password Reset Views
    path("password_reset/", auth_views.PasswordResetView.as_view(), name='password_reset'),
    path("password_reset/done/", auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path("reset/<uidb64>/<token>/", auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path("reset/done/", auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),


    path("", include('matrimony.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

matrimony/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name="matrimony"

urlpatterns = [
    path('', views.ProfileListView, name='profile_list'),
    path('<int:profile_id>', views.ProfileDetailView, name='profile_detail'),
    path('<int:profile_id>/delete', views.ProfileDeleteView, name='delete'),
    path('contact', views.ContactView, name='contact'),
    path('new_profile', views.ProfileFormView, name='new_profile'),
    path('father_profile', views.FatherProfileView, name='father_profile'),

]

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
        <link rel="stylesheet" href="{% static 'matrimony/css/styles.css' %}">
        {% block title %}
        <title>Matrimony App</title>
        {% endblock%}
    </head>

    <body>

        {% include "header.html" %}

        <p></p>

        <main role="main" class="container">
            {% block content %}
            {% endblock content %}
        </main>

        <p></p>

        {% include "footer.html" %}

        <!-- Load Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz"
            crossorigin="anonymous"></script>
    </body>

</html>

templates/footer.html
<section class="footer">
  
      <!-- Copyright -->
      <div class="text-white text-center p-2 fixed-bottom" style="background-color: #0a4275;">
        © 2024 Copyright:
        <a class="text-white" href="https://manandevpro.com/">John Doe</a>
      </div>
      <!-- Copyright -->
    </footer>
    <!-- Footer -->
  </section>

templates/header.html
{% load static %}

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="#"><img src="{% static 'images/logo.png' %}" alt="logo" width="50px"><b>Matrimonial App</b></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'matrimony:profile_list' %}">Home</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'matrimony:contact' %}">Contact Us</a>
      </li>
    </ul>

    {% if user.is_authenticated %}
    <ul id="logged-in" class="navbar-nav ml-auto">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle text-white" role="button" data-toggle="dropdown"
          href="#">{{ user.username }}</a>
        <div class="dropdown-menu dropdown-menu-right">
          <a class="dropdown-item" href="{% url 'password_change' %}">Change Password</a>
          <a class="dropdown-item" href="{% url 'accounts:delete' %}">Delete Account</a>
          <a class="dropdown-item" id="logout-btn" href="{% url 'accounts:logout' %}">Logout</a>
        </div>
      </li>
    </ul>
    {% endif %}

  </div>
</nav>

<script> var csrfToken = '{{ csrf_token }}'; </script>
<script src="{% static 'js/header.js' %}"></script>